# -*- coding: utf-8 -*-
"""level2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wp9EgJAiuMbGVYgErzSYBsdI9VZuTbnS
"""

phone_book = ["119", "97674223", "1195524421"]

def solution(phone_book):
    answer = True
    flag = True
    
    for a in phone_book:
        if flag == False:
            break
        for b in phone_book:
            if a.find(b) == 0 and a!=b:
                answer = False
                flag = False
                break
        
    return answer

print(solution(phone_book))

