# -*- coding: utf-8 -*-
"""level3_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wp9EgJAiuMbGVYgErzSYBsdI9VZuTbnS
"""

numbers = [6,10,2]

from itertools import permutations
def solution(numbers):
    answer = ''
    # options = []
    # permute = list(permutations(numbers,len(numbers)))
    # options = [''.join(map(str,arr)) for arr in permute]
    # answer = max(options)
    
    answer = sorted(list(map(str,numbers)), key = lambda x: x*4, reverse = True)
    
    return str(int(''.join(answer)))

solution(numbers)

