# -*- coding: utf-8 -*-
"""level1_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wp9EgJAiuMbGVYgErzSYBsdI9VZuTbnS
"""

def solution(array, commands):
  answer = []

  for arr in commands:
    new_array = array[arr[0]-1:arr[1]]
    new_array.sort()
    result = new_array[arr[2]-1]
    answer.append(result)
  
  return answer